### ISSUE TITLE
output file names does not contain the code HNS/HLS/etc. 

### ISSUE THREAD

**Issue by avanaudenhaege** [SteMat9787/SIGN_LANGUAGE_VWFA_fMRIexperiments#3]
Therefore HLS002 **would overwrite** previous 002 subject. 
Either we give numbers not overlapping across groups (e.g. follow real order, HNS001 then HLS002) 
OR 
We make the code of the subject alphanumeric --> sub-HNS001 and sub-HLS001 (I'm 95% sure this is ok in bids)

**Comment by SteMat9787** [comment]
I prefer the second option. I changed the name of the .tsv file now so they will not overlap. 
Also, this format is now 100% BIDS compatible: it is the format I used to run the conversion in subject HNS1 and HNS2, so it should be fine. 

Side note: I think that in any case we should empty the output file folder after each subject, so that the only output files that we get are the ones from the current subject.
